# Generated by Django 5.1.5 on 2025-01-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_id',
            field=models.CharField(default=2290, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
