# Generated by Django 5.1.5 on 2025-01-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='custom_id',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
